### ISSUE TITLE
National Map - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#12]
A geographical map of the country including national traffic routes, stretches of water, and markings of heights. The map must at least be provided at a scale of 1:250,000 (1 cm = 2.5km).

- Scale of 1:250,000 (1 cm = 2.5km)
- Markings of national traffic routes
- Markings of relief/heights
- Markings of water stretches
- National borders

http://global.survey.okfn.org/dataset/map

**Comment by andreskytt** [comment]
Available at http://geoportaal.maaamet.ee/est/Andmed-ja-kaardid-p1.html. Close, if sufficient.

**Comment by iseppo** [comment]
The problem here is the license - most of the EU countries offer the maps under completely free license, but not Estonia. This should be thought through and at least some of the data should be put under a more permissive license. I can not for example create an R package with Estonian counties under current license.

this is what they write at the link: 
"Ruumiandmed antakse kasutusse tasu eest või tasuta. Tasuta on andmed teabevaldajale (AvTS §5 lg1) ehk avalik-õiguslikele juriidilistele isikutele (näiteks riigiasutustele), kohalikele omavalitsustele ja sellistele eraõiguslikele juriidilistele isikutele, kellele on seadusega või täidesaatva riigivõimu asutuse poolt halduslepinguga pandud kaartide kasutamist eeldavate avalike ülesannete täitmise kohustus. Kohustuse olemasolu põhjendab andmete taotleja. Tasuta on andmed ka Euroopa Liidu liikmesriikide avaliku võimu kandjatele ning Euroopa Liidu institutsioonidele selliste avalik-õiguslike ülesannete täitmiseks, mis võivad mõjutada keskkonda. Õppe- ja teadustööks on andmete kasutusõigus tasuta avalik-õigusliku juriidilise isiku staatusega ülikoolidele (näiteks Tartu Ülikoolile, Tallinna Tehnikaülikoolile, Tallinna Ülikoolile, Eesti Maaülikoolile, Eesti Kunstiakadeemiale ning Eesti Muusika- ja Teatriakadeemiale) ning hallatava riigiasutuse staatusega õppeasutustele. Eraõiguslikele juriidilistele isikutele (äriühingud, mittetulundusühingud) ning füüsilistele isikutele on andmed tasu eest."

**Comment by jaakla** [comment]
It is not only license, but also availability and cost. The Maaamet page lists all datasets they manage, only some of them are downloadable or open. For example administrative borders are downloadable as vector map data, but most others are not, or as published as not machine-readable raster images in web (html or WMS). Most of the other datasets have to be purchased, so complete country datasets may cost tens of €.

**Comment by infokujur** [comment]
Is it still a problem, we tried, it worked? @jaakla format not good though.

**Comment by infokujur** [comment]
Maaametil on olemas viide opendata.riik.ee portaali https://opendata.riik.ee/andmehulgad/maa-ameti-avaandmete-portaal/
Palun uuendada infot nii, et opendata.riik.ee-l oleks viidatud ka andmehulgad https://geoportaal.maaamet.ee/est/Andmete-tellimine/Avaandmed/Eesti-topograafia-andmekogu-ruumiandmed-p607.html
