### ISSUE TITLE
Locations datasets - Open Data Index

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/opendata-issue-tracker#2]
A database of postcodes/zipcodes and the corresponding spatial locations in terms of a latitude and a longitude (or similar coordinates in an openly published coordinate system). The data has to be available for the entire country.

A database of postcodes/zipcodes and the corresponding spatial locations in terms of a latitude and a longitude (or similar coordinates in an openly published coordinate system). The data has to be available for the entire country.

- Zipcodes
- Addresses
- Coordinates (latitude, longitude)
- Data available for entire country

http://global.survey.okfn.org/dataset/postcodes

**Comment by andreskytt** [comment]
http://postiindeks.ee/ has a neat search engine with all the data but I could not find a source

**Comment by peepkungas** [comment]
This data is currently provided by Maaamet. We (at Register OÜ) are in the phase of releasing continuously updated ADS data (plus the post indices they provide) via our Graph API. Access to this dataset will be provided via our Open Data Plan offering.

**Comment by andreskytt** [comment]
Please comment, once the data is indeed available

**Comment by tormi** [comment]
> This data is currently provided by Maaamet.

@peepkungas, which data? Addresses with or without zipcodes?

**Comment by andreskytt** [comment]
Have forwarded this to KEMIT technical folks for review. @tormi, do you have anything more specific in mind than "I want to be able to query the address dataset by all elements of the data model via a JSON API"?

**Comment by tormi** [comment]
@andreskytt , thanks! 

> do you have anything more specific in mind

Here are few fetching features I'm interested in, but not currently possible:

1. [Filtering](http://jsonapi.org/format/#fetching-filtering). This is basically "_I want to be able to query the address dataset by all elements of the data model_"
2. [Sparse Fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets), ie fetch only fields that are needed.
3. [Pagination](http://jsonapi.org/format/#fetching-pagination). Current query limit is max 100 items and there is no pagination. So I cant query all addresses of my village because there's more than 100.

**Comment by tkardi** [comment]
In the case of Estonia postal codes do not form "areas", separate polygons that could be delineated. A postal code is simply a numeric attribute that can be assigned to an address. There have been efforts by the Land Board to incorporate postal code data into ADS aswell, I don't know the current situation.

@tormi you can do inaddress search by cadastral id aswell e.g http://inaadress.maaamet.ee/inaadress/gazetteer?address=79506:003:0026. But as with all other addressable objects it only returns the bounding box + "labelling point" of the cadastral parcel and not the object itself. 

inaddress is a geocoding tool, and it's purpose is turning location description text into location and vice-versa. It's not intended for bulk data downloads. 

If you want to get the full dataset, then you can download the respective csv files from http://xgis.maaamet.ee/adsavalik/ads (click "Väljavõtted" on the menubar). The whole process is very tedious and since the csv file download urls are not fixed it will be very difficult to automate download on the user's side. I feel that in terms of OD this is something that should be enhanced/made easier/friendlier.

**Comment by tormi** [comment]
> you can do inaddress search by cadastral id aswell

Wow, what a hackish and illogical, also undocumented feature! Would expect sth like [http://inaadress.maaamet.ee/inaadress/gazetteer?**tunnus**=79506:003:0026](http://inaadress.maaamet.ee/inaadress/gazetteer?tunnus=79506:003:0026) at least :)

JSON API equivalent would be:

`GET /addresses?fields[addresses]=viitepunkt_x,viitepunkt_y,pikkaadress,aadresstekst,koodaadress,boundingbox,ehakov,liik,ehak,tunnus,taisaadress,ehakmk,onkort,liikVal,ads_oid&filter[tunnus][value]=79506:003:0026`

> inaddress is a geocoding tool, and it's purpose is turning location description text into location and vice-versa. It's not intended for bulk data downloads.

I know.  That's why I referred here with remark _sort of_ since there's no other ADS API's available. 

> If you want to get the full dataset, then you can download the respective csv files

.. starting 1 GB ;)

> I feel that in terms of OD this is something that should be enhanced/made easier/friendlier.

Via JSON API? :D

>  since the ... urls are not fixed 

Also covered in [JSON API (fetching-resources)](http://jsonapi.org/format/#fetching-resources).
`
### Conclusion

**It would be so much easier and predictable if agencies are required to use agreed spec when implemeting their OD solutions.** JSON API can be their (and also data consumer's) anti-[bikeshedding](http://bikeshed.org/) tool and therefore a real time and money saver.

**Comment by peepkungas** [comment]
We have released the ADS data as linked and continuously updated dataset via Graph API v3. Query examples: 
1) https://graph.ir.ee/v3/sites/ee-10000018-registered  - links to the registered address and an address object of the corresponding address of company with reg code 10000018. 
2) https://graph.ir.ee/v3/address-objects/me01835474 - address object data, also links to companies registered to the same address object (building)
3) https://graph.ir.ee/v3/addresses/2125797 - address data including references to previous address versions, address components, coordinates, postal codes etc
4) https://graph.ir.ee/v3/address-components/3-0339 - address component data with reference to master component

Further details available at https://developers.ir.ee/graph-api .

**Comment by andreskytt** [comment]
ZIP Codes live in a ZIP file on this page: http://geoportaal.maaamet.ee/est/Andmed-ja-kaardid/Aadressiandmed/Aadressid-ja-posti-sihtnumbrid-e-indeksid-p582.html

**Comment by andreskytt** [comment]
The file does not contain coordinates but a ADR_ID that should be possible to resolve into geographical coordinates using the address database.
